name: Cancel Specific Workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the workflow run to cancel'
        required: true

jobs:
  cancel_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cancel workflow
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          run_id: ${{ github.event.inputs.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN3 }}
